// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvfX5S5vosfC2bxryLStv_kb9jLoENsLg',
    appId: '1:741385998298:web:429fc9bfecdd6d2e25bae3',
    messagingSenderId: '741385998298',
    projectId: 'josariyaw',
    authDomain: 'josariyaw.firebaseapp.com',
    storageBucket: 'josariyaw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUvHfEQXvrVvF7U0W6DZKl46SSBzIIbFk',
    appId: '1:741385998298:android:b504c673cd7df87825bae3',
    messagingSenderId: '741385998298',
    projectId: 'josariyaw',
    storageBucket: 'josariyaw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOasOhU9Rmj3XbyiOVsDWYHV__gdPxQKI',
    appId: '1:741385998298:ios:a8cf7320428c7e7925bae3',
    messagingSenderId: '741385998298',
    projectId: 'josariyaw',
    storageBucket: 'josariyaw.appspot.com',
    iosBundleId: 'com.example.josariyaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvfX5S5vosfC2bxryLStv_kb9jLoENsLg',
    appId: '1:741385998298:web:f43e5c65d90c23ae25bae3',
    messagingSenderId: '741385998298',
    projectId: 'josariyaw',
    authDomain: 'josariyaw.firebaseapp.com',
    storageBucket: 'josariyaw.appspot.com',
  );
}
